---

- name: Check for certificate
  stat:
    path: "{{ tls_cert_path }}/{{ item.common_name }}/cert.pem"
  register: tls_cert_certstat

- name: Fetch CA issuer URI.
  shell: >
     openssl x509 -in
     {{ tls_cert_path }}/{{ item.common_name }}/cert.pem
     -text -noout -certopt ca_default,no_validity,no_serial |
     grep -E '^\s+CA\s+Issuers\s+-\s+URI:' |
     awk '{print $4}' |
     sed -e 's/^URI://'
  changed_when: false
  register: tls_cert_ca_issuer_uri
  when: "{{ tls_cert_certstat.stat.exists | default(false) }}"

- include: chain-issuers.yml
  with_indexed_items:
    - "{{ tls_cert_ca_issuer_uri.stdout_lines }}"
  when: tls_cert_ca_issuer_uri.stdout_lines | default(false)
  loop_control:
    loop_var: issuer_uri
  tags:
  - tls_cert_chain
  - tls_cert_chain_issuers

#- debug:
#    msg: >
#      {{ tls_cert_ca_issuer_uri.stdout_lines }}
#  when: "{{ tls_cert_ca_issuer_uri.stdout_lines | default(false) }}"
