---

# We'll use Diffie Hellman key exchange to improve the forward security of
# communication.  This means the servers private keys are not directly used
# when encrypting data.
- name: Diffie Hellman ephemeral parameters
  command: openssl dhparam -out dhparam.pem 4096
  args:
    chdir: "{{ tls_cert_path }}"
    creates: "{{ tls_cert_path }}/dhparam.*"

# Make sure this file is automatically protected by vault.
- name: Encrypted Diffie Hellman ephemeral parameters exists.
  command: >
    ansible-vault encrypt
    {{ tls_cert_path }}/dhparam.pem
    --output={{ tls_cert_path }}/dhparam.vault.yml
  args:
    chdir: "{{ tls_cert_path }}/.."
    creates: "{{ tls_cert_path }}/dhparam.vault.yml"

- name: Unencrypted Diffie Hellman ephemeral parameters absent.
  file:
    path: "{{ tls_cert_path }}/dhparam.pem"
    state: absent
