---
# tasks file for tls-cert

- include: yum.yml
  when: (((ansible_distribution == "CentOS") or (ansible_distribution == "RedHat")) and (ansible_distribution_major_version == "7"))
  become: true
  tags:
  - tls_cert_yum

- include: config.yml
  tags:
  - tls_cert_config

- include: dhparam.yml
  tags:
  - tls_cert_dhparam

- include: req.yml
  tags:
  - tls_cert_req
  with_items: "{{ tls_certificates }}"

- include: self-signed.yml
  tags:
  - tls_cert_self_signed
  with_items: "{{ tls_certificates }}"
  when: item.type == "self-signed"

- include: acme.yml
  tags:
  - tls_cert_acme

- include: olde-style.yml
  tags:
  - tls_cert_olde_style
  with_items: "{{ tls_certificates }}"
  when: item.type == "olde-style"

- include: chain.yml
  tags:
  - tls_cert_chain
  with_items: "{{ tls_certificates }}"
  when: item.type != "self-signed"
