---
# tasks file for tls-cert

- include: yum.yml
  when: (((ansible_distribution == "CentOS") or (ansible_distribution == "RedHat")) and (ansible_distribution_major_version == "7"))
  become: true
  tags:
  - tls_cert_yum

- include: config.yml
  tags:
  - tls_cert_config

- include: req.yml
  tags:
  - tls_cert_req

- include: x509.yml
  tags:
  - tls_cert_x509

- include: acme.yml
  tags:
  - tls_cert_acme
