---

- name: Check for olde stle certificate
  stat:
    path: "{{ tls_cert_path }}/{{ item.common_name }}/cert.pem"
  register: tls_cert_certstat

- name: Check for olde stle certificate chain
  stat:
    path: "{{ tls_cert_path }}/{{ item.common_name }}/chain.pem"
  register: tls_cert_chainstat

- name: Fullchain exists for olde style certificate
  shell: >
    cat cert.pem chain.pem >> fullchain.pem &&
    sed -i 's/-----END CERTIFICATE----------BEGIN CERTIFICATE-----/-----END CERTIFICATE-----\n-----BEGIN CERTIFICATE-----/' fullchain.pem
  args:
    chdir: "{{ tls_cert_path }}/{{ item.common_name }}"
    creates: "{{ tls_cert_path }}/{{ item.common_name }}/fullchain.pem"
  when: tls_cert_certstat.stat.exists and tls_cert_chainstat.stat.exists
