---

- name: TLS cert directory exists
  file:
    path: "{{ tls_cert_path }}/{{ item.common_name }}"
    state: directory

- name: copy openssl.cnf
  template:
    src: openssl.cnf.j2
    dest: "{{ tls_cert_path }}/{{ item.common_name }}/openssl.cnf"

- name: TLS key and CSR exist.
  shell: >
     openssl req -new -newkey rsa -nodes
     -config {{ tls_cert_path }}/{{ item.common_name }}/openssl.cnf 
     -keyout {{ tls_cert_path }}/{{ item.common_name }}/privkey.pem
     -out {{ tls_cert_path }}/{{ item.common_name }}/request.csr
  args:
    creates: "{{ tls_cert_path }}/{{ item.common_name }}/privkey.*"

- name: Encrypted TLS key exists.
  command: >
    ansible-vault encrypt
    {{ tls_cert_path }}/{{ item.common_name }}/privkey.pem
    --output={{ tls_cert_path }}/{{ item.common_name }}/privkey.vault.yml
  args:
    chdir: "{{ tls_cert_path}}/.."
    creates: "{{ tls_cert_path }}/{{ item.common_name }}/privkey.vault.yml"

- name: Unencrypted TLS key is absent.
  file:
    path: "{{ tls_cert_path }}/{{ item.common_name }}/privkey.pem"
    state: absent
