---

- name: TLS cert directory exists
  file:
    path: "{{ tls_cert_path }}/{{ item.name }}"
    state: directory
  with_items: "{{ tls_certificates }}"

- name: TLS key and CSR exist.
  shell: >
     TLS_CERT_CN="{{ item.common_name }}" TLS_CERT_SAN="{{ item.alt_names }}"
     openssl req -config ~/openssl.cnf -new -newkey rsa -nodes
     -keyout "{{ tls_cert_path }}"/"{{ item.name }}"/privkey.pem
     -out "{{ tls_cert_path }}"/"{{ item.name }}"/request.csr
  args:
    creates: "{{ tls_cert_path }}/{{ item.name }}/privkey.pem"
  with_items: "{{ tls_certificates }}"
  environment:
    TLS_CERT_C: "{{ tls_cert_country }}"
    TLC_CERT_ST: "{{ tls_cert_state }}"
    TLS_CERT_L: "{{ tls_cert_locality }}"
    TLS_CERT_O: "{{ tls_cert_organization }}"
    TLS_CERT_OU: "{{ tls_cert_department }}"
