---

- name: TLS cert directory exists
  file:
    path: "{{ tls_cert_path }}/{{ item.common_name }}"
    state: directory
  with_items: "{{ tls_certificates }}"

- name: TLS key and CSR exist.
  shell: >
     TLS_CERT_CN={{ item.common_name }} {% if item.alt_names is defined %}TLS_CERT_SAN={{ item.alt_names }}{% endif %}
     openssl req -config {{ tls_cert_path }}/openssl.cnf -new -newkey rsa -nodes
     -keyout {{ tls_cert_path }}/{{ item.common_name }}/privkey.pem
     -out {{ tls_cert_path }}/{{ item.common_name }}/request.csr
  args:
    creates: "{{ tls_cert_path }}/{{ item.common_name }}/privkey.*"
  with_items: "{{ tls_certificates }}"
  environment:
    TLS_CERT_C: "{{ tls_cert_country }}"
    TLC_CERT_ST: "{{ tls_cert_state }}"
    TLS_CERT_L: "{{ tls_cert_locality }}"
    TLS_CERT_O: "{{ tls_cert_organization }}"
    TLS_CERT_OU: "{{ tls_cert_department }}"
