---

- name: Unencrypted TLS key exists.
  command: >
    ansible-vault decrypt
    {{ tls_cert_path }}/{{ item.common_name }}/privkey.vault.yml
    --output={{ tls_cert_path }}/{{ item.common_name }}/privkey.pem
  args:
    chdir: "{{ tls_cert_path}}/.."
    creates: "{{ tls_cert_path }}/{{ item.common_name }}/privkey.pem"
  when: item.type == "self-signed"

- name: Self-signed TLS key exists.
  shell: >
     openssl x509 -req -extensions v3_req
     -extfile "{{ tls_cert_path }}/{{ item.common_name }}/openssl.cnf"
     -in "{{ tls_cert_path }}/{{ item.common_name }}/request.csr"
     -signkey "{{ tls_cert_path }}/{{ item.common_name }}/privkey.pem"
     -out "{{ tls_cert_path }}/{{ item.common_name }}/fullchain.pem"
  args:
    creates: "{{ tls_cert_path }}/{{ item.common_name }}/fullchain.pem"
  when: item.type == "self-signed"

- name: Unencrypted TLS key is absent.
  file:
    path: "{{ tls_cert_path }}/{{ item.common_name }}/privkey.pem"
    state: absent
  when: item.type == "self-signed"
