---

- name: Self-signed TLS key exists.
  shell: >
     openssl x509 -req
     -in "{{ tls_cert_path }}"/"{{ item.common_name }}"/request.csr
     -signkey "{{ tls_cert_path }}"/"{{ item.common_name }}"/privkey.pem
     -out "{{ tls_cert_path }}"/"{{ item.common_name }}"/fullchain.pem
  args:
    creates: "{{ tls_cert_path }}/{{ item.common_name }}/fullchain.pem"
  with_items: "{{ tls_certificates }}"
  when: item.type == "self-signed"
